version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - postgres
    restart: unless-stopped
    command: >
      sh -c "composer install && sleep 5 && php artisan migrate && php artisan serve --host=0.0.0.0 --port=8000"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
