version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - postgres
    restart: unless-stopped
    command: >
      sh -c "composer install && sleep 5 && php artisan migrate && php artisan serve --host=0.0.0.0 --port=8000"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: koyebdb
      POSTGRES_USER: koyeb-adm
      POSTGRES_PASSWORD: npg_Y7Ifbv3BuzKJ
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:


networks:
  app-network:
    driver: bridge