version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

